/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dentistas;

import javax.swing.JLabel;
import javax.swing.table.TableColumn;

public class Principal extends javax.swing.JFrame {

    //Inicializo objetos, en estas clases se encuentran los metodos de cada pestaña
    Configuracion config = new Configuracion(); //Creo objetos de configuracion
    Hoy cHoy = new Hoy(); //Creo objetos de tab Hoy
    
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        super("Programa dentistas por Daniel y Hector");
        initComponents();
        
        //Añado al label la fecha actual
        fecha_actual.setText(config.fecha_actual());
        
        //Este metodo crea la tabla y muestra los resultados en la tabla
        //Se le pasa un jTable (tablaHoy) e implementa un modelo
        cHoy.tablaHoy(tablaHoy);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabHoy = new javax.swing.JPanel();
        fecha_label = new java.awt.Label();
        fecha_actual = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHoy = new javax.swing.JTable();
        tabAgenda = new javax.swing.JPanel();
        tabPacientes = new javax.swing.JPanel();
        tabFacturas = new javax.swing.JPanel();
        tabConfiguracion = new javax.swing.JPanel();
        tabHistorias = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(217, 244, 255));
        setMinimumSize(new java.awt.Dimension(800, 700));

        jTabbedPane1.setBackground(new java.awt.Color(198, 242, 255));

        tabHoy.setPreferredSize(new java.awt.Dimension(800, 700));

        fecha_label.setText("Fecha de hoy: ");

        jScrollPane1.setEnabled(false);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(500, 560));
        jScrollPane1.setName(""); // NOI18N

        tablaHoy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaHoy);

        javax.swing.GroupLayout tabHoyLayout = new javax.swing.GroupLayout(tabHoy);
        tabHoy.setLayout(tabHoyLayout);
        tabHoyLayout.setHorizontalGroup(
            tabHoyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabHoyLayout.createSequentialGroup()
                .addGroup(tabHoyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabHoyLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(fecha_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fecha_actual, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabHoyLayout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabHoyLayout.setVerticalGroup(
            tabHoyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabHoyLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(tabHoyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fecha_actual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecha_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        fecha_label.getAccessibleContext().setAccessibleName("fecha_label");
        fecha_actual.getAccessibleContext().setAccessibleName("fecha_hoy");
        fecha_actual.getAccessibleContext().setAccessibleDescription("");

        jTabbedPane1.addTab("Hoy", tabHoy);

        javax.swing.GroupLayout tabAgendaLayout = new javax.swing.GroupLayout(tabAgenda);
        tabAgenda.setLayout(tabAgendaLayout);
        tabAgendaLayout.setHorizontalGroup(
            tabAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        tabAgendaLayout.setVerticalGroup(
            tabAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Agenda", tabAgenda);

        javax.swing.GroupLayout tabPacientesLayout = new javax.swing.GroupLayout(tabPacientes);
        tabPacientes.setLayout(tabPacientesLayout);
        tabPacientesLayout.setHorizontalGroup(
            tabPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        tabPacientesLayout.setVerticalGroup(
            tabPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Pacientes", tabPacientes);

        javax.swing.GroupLayout tabFacturasLayout = new javax.swing.GroupLayout(tabFacturas);
        tabFacturas.setLayout(tabFacturasLayout);
        tabFacturasLayout.setHorizontalGroup(
            tabFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        tabFacturasLayout.setVerticalGroup(
            tabFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Facturas", tabFacturas);

        javax.swing.GroupLayout tabConfiguracionLayout = new javax.swing.GroupLayout(tabConfiguracion);
        tabConfiguracion.setLayout(tabConfiguracionLayout);
        tabConfiguracionLayout.setHorizontalGroup(
            tabConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        tabConfiguracionLayout.setVerticalGroup(
            tabConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Historias", tabConfiguracion);

        javax.swing.GroupLayout tabHistoriasLayout = new javax.swing.GroupLayout(tabHistorias);
        tabHistorias.setLayout(tabHistoriasLayout);
        tabHistoriasLayout.setHorizontalGroup(
            tabHistoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        tabHistoriasLayout.setVerticalGroup(
            tabHistoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Configuración", tabHistorias);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //Guardo el Jframe en un objeto
                Principal Jframe = new Principal();
                //PrincipalHoy es el Jframe, indico que al iniciarse se maximice la ventana
                Jframe.setExtendedState(MAXIMIZED_BOTH);
                Jframe.setVisible(true);
            }
        });
        
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label fecha_actual;
    private java.awt.Label fecha_label;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel tabAgenda;
    private javax.swing.JPanel tabConfiguracion;
    private javax.swing.JPanel tabFacturas;
    private javax.swing.JPanel tabHistorias;
    private javax.swing.JPanel tabHoy;
    private javax.swing.JPanel tabPacientes;
    private javax.swing.JTable tablaHoy;
    // End of variables declaration//GEN-END:variables
}
